## Heart Attack Prediction

In [12]:
# load the libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from joblib import dump, load
from sklearn.compose import ColumnTransformer

In [13]:
# load the data
# Assicurati di aver scaricato il CSV da Kaggle e messo in '../data/heart.csv'
data = pd.read_csv('../data/heart.csv')

In [14]:
# check the target variable distribution
# La colonna target in questo dataset si chiama 'output'
print(data.output.value_counts())

output
1    165
0    138
Name: count, dtype: int64

In [15]:
# check the first few rows of the data
data.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

### Data Preprocessing

In [17]:
### Data Preprocessing

# 1. Definiamo i tipi di colonne
# Colonne numeriche che vogliamo scalare
numerical_cols = ['age', 'trtbps', 'chol', 'thalachh', 'oldpeak']

# Colonne categoriche (già in formato numerico) che lasceremo invariate
categorical_cols = ['sex', 'cp', 'fbs', 'restecg', 'exng', 'slp', 'caa', 'thall']

# Colonna Target
target_col = 'output'

# 2. Separiamo features (x) e target (y)
y = data[target_col]
x = data.drop(target_col, axis = 1)

# 3. Creiamo il ColumnTransformer
# Questo oggetto applicherà lo StandardScaler SOLO alle 'numerical_cols'
# e lascerà invariate ('passthrough') le 'categorical_cols'
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', 'passthrough', categorical_cols)
    ],
    remainder='drop' # Ignora colonne non specificate
)

# 4. Applichiamo il fit_transform
# 'features' ora è il nostro set di dati processato
features_processed = preprocessor.fit_transform(x)

# 5. Ricreiamo il DataFrame processato (per coerenza)
# L'ordine delle colonne sarà prima 'numerical_cols' e poi 'categorical_cols'
final_columns_ordered = numerical_cols + categorical_cols
features = pd.DataFrame(features_processed, columns = final_columns_ordered)

# Stampa di controllo
print(f"Ordine finale delle colonne: {final_columns_ordered}")
features.head()

Ordine finale delle colonne: ['age', 'trtbps', 'chol', 'thalachh', 'oldpeak', 'sex', 'cp', 'fbs', 'restecg', 'exng', 'slp', 'caa', 'thall']

,age,trtbps,chol,thalachh,oldpeak,sex,cp,fbs,restecg,exng,slp,caa,thall
0,0.952197,0.763956,-0.256334,0.015443,1.087338,1.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0
1,-1.915313,-0.092738,0.072199,1.633471,2.122573,1.0,2.0,0.0,1.0,0.0,0.0,0.0,2.0
2,-1.474158,-0.092738,-0.816773,0.977514,0.310912,0.0,1.0,0.0,0.0,0.0,2.0,0.0,2.0
3,0.180175,-0.663867,-0.198357,1.239897,-0.206705,1.0,1.0,0.0,1.0,0.0,2.0,0.0,2.0
4,0.290464,-0.663867,2.082050,0.583939,-0.379244,0.0,0.0,0.0,1.0,1.0,2.0,0.0,2.0

In [18]:
# save the preprocessor (che agisce come il nostro scaler)
dump(preprocessor, '../models/scaler.joblib')

['../models/scaler.joblib']

### Modelling

In [19]:
# split the data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(features, y, test_size = 0.2, random_state = 42)

In [20]:
# define the model
model = MLPClassifier(solver="adam", max_iter=1000, activation="relu", hidden_layer_sizes=(12), alpha=0.001, batch_size=32, learning_rate_init=0.0001, random_state=42, verbose=True)
# fit the model
model.fit(x_train, y_train.values.ravel())

Iteration 1, loss = 0.71763246
Iteration 2, loss = 0.71578716
Iteration 3, loss = 0.71404768
Iteration 4, loss = 0.71235432
Iteration 5, loss = 0.71074342
Iteration 6, loss = 0.70900422
Iteration 7, loss = 0.70740038
Iteration 8, loss = 0.70568009
Iteration 9, loss = 0.70409167
Iteration 10, loss = 0.70252172
Iteration 11, loss = 0.70081863
Iteration 12, loss = 0.69930666
Iteration 13, loss = 0.69766307
Iteration 14, loss = 0.69615634
Iteration 15, loss = 0.69460629
Iteration 16, loss = 0.69300566
Iteration 17, loss = 0.69156178
Iteration 18, loss = 0.69003570
Iteration 19, loss = 0.68856291
Iteration 20, loss = 0.68701144
Iteration 21, loss = 0.68563563
Iteration 22, loss = 0.68413174
Iteration 23, loss = 0.68265190
Iteration 24, loss = 0.68121077
Iteration 25, loss = 0.67986676
Iteration 26, loss = 0.67837770
Iteration 27, loss = 0.67694687
Iteration 28, loss = 0.67554334
Iteration 29, loss = 0.67424915
Iteration 30, loss = 0.67276592
Iteration 31, loss = 0.67139889
Iteration 32, loss = 0.67000857
Iteration 33, loss = 0.66868425
Iteration 34, loss = 0.66736169
Iteration 35, loss = 0.66589152
Iteration 36, loss = 0.66459124
Iteration 37, loss = 0.66328159
Iteration 38, loss = 0.66191586
Iteration 39, loss = 0.66065943
Iteration 40, loss = 0.65935966
Iteration 41, loss = 0.65805292
Iteration 42, loss = 0.65673920
Iteration 43, loss = 0.65544059
Iteration 44, loss = 0.65415652
Iteration 45, loss = 0.65287269
Iteration 46, loss = 0.65166412
Iteration 47, loss = 0.65036219
Iteration 48, loss = 0.64916678
Iteration 49, loss = 0.64794117
Iteration 50, loss = 0.64670923
Iteration 51, loss = 0.64551420
Iteration 52, loss = 0.64423402
Iteration 53, loss = 0.64307127
Iteration 54, loss = 0.64181420
Iteration 55, loss = 0.64062236
Iteration 56, loss = 0.63944356
Iteration 57, loss = 0.63825482
Iteration 58, loss = 0.63707048
Iteration 59, loss = 0.63585603
Iteration 60, loss = 0.63470505
Iteration 61, loss = 0.63352957
Iteration 62, loss = 0.63238260
Iteration 63, loss = 0.63118553
Iteration 64, loss = 0.63003911
Iteration 65, loss = 0.62886882
Iteration 66, loss = 0.62770152
Iteration 67, loss = 0.62655430
Iteration 68, loss = 0.62540471
Iteration 69, loss = 0.62424461
Iteration 70, loss = 0.62307021
Iteration 71, loss = 0.62194636
Iteration 72, loss = 0.62078050
Iteration 73, loss = 0.61960896
Iteration 74, loss = 0.61848563
Iteration 75, loss = 0.61728005
Iteration 76, loss = 0.61612980
Iteration 77, loss = 0.61500795
Iteration 78, loss = 0.61384019
Iteration 79, loss = 0.61274097
Iteration 80, loss = 0.61163694
Iteration 81, loss = 0.61050641
Iteration 82, loss = 0.60946023
Iteration 83, loss = 0.60830119
Iteration 84, loss = 0.60713192
Iteration 85, loss = 0.60603622
Iteration 86, loss = 0.60495826
Iteration 87, loss = 0.60379814
Iteration 88, loss = 0.60266597
Iteration 89, loss = 0.60156622
Iteration 90, loss = 0.60044154
Iteration 91, loss = 0.59933714
Iteration 92, loss = 0.59821587
Iteration 93, loss = 0.59716620
Iteration 94, loss = 0.59602831
Iteration 95, loss = 0.59499160
Iteration 96, loss = 0.59389741
Iteration 97, loss = 0.59284804
Iteration 98, loss = 0.59174303
Iteration 99, loss = 0.59066522
Iteration 100, loss = 0.58953245
Iteration 101, loss = 0.58845220
Iteration 102, loss = 0.58738805
Iteration 103, loss = 0.58629070
Iteration 104, loss = 0.58520132
Iteration 105, loss = 0.58411880
Iteration 106, loss = 0.58309136
Iteration 107, loss = 0.58195502
Iteration 108, loss = 0.58089686
Iteration 109, loss = 0.57976163
Iteration 110, loss = 0.57864927
Iteration 111, loss = 0.57756719
Iteration 112, loss = 0.57646686
Iteration 113, loss = 0.57531826
Iteration 114, loss = 0.57422733
Iteration 115, loss = 0.57312779
Iteration 116, loss = 0.57208470
Iteration 117, loss = 0.57098342
Iteration 118, loss = 0.56984891
Iteration 119, loss = 0.56880299
Iteration 120, loss = 0.56773287
Iteration 121, loss = 0.56657620
Iteration 122, loss = 0.56548137
Iteration 123, loss = 0.56437913
Iteration 124, loss = 0.56331159
Iteration 125, loss = 0.56223074
Iteration 126, loss = 0.56121140
Iteration 127, loss = 0.56016494
Iteration 128, loss = 0.55910520
Iteration 129, loss = 0.55805478
Iteration 130, loss = 0.55708633
Iteration 131, loss = 0.55604201
Iteration 132, loss = 0.55500724
Iteration 133, loss = 0.55400237
Iteration 134, loss = 0.55304358
Iteration 135, loss = 0.55205667
Iteration 136, loss = 0.55102751
Iteration 137, loss = 0.55007323
Iteration 138, loss = 0.54910557
Iteration 139, loss = 0.54817352
Iteration 140, loss = 0.54720322
Iteration 141, loss = 0.54624521
Iteration 142, loss = 0.54530065
Iteration 143, loss = 0.54434214
Iteration 144, loss = 0.54339378
Iteration 145, loss = 0.54242511
Iteration 146, loss = 0.54149750
Iteration 147, loss = 0.54058318
Iteration 148, loss = 0.53963638
Iteration 149, loss = 0.53871740
Iteration 150, loss = 0.53781062
Iteration 151, loss = 0.53685254
Iteration 152, loss = 0.53599031
Iteration 153, loss = 0.53501729
Iteration 154, loss = 0.53412033
Iteration 155, loss = 0.53320086
Iteration 156, loss = 0.53228420
Iteration 157, loss = 0.53138220
Iteration 158, loss = 0.53051135
Iteration 159, loss = 0.52960367
Iteration 160, loss = 0.52866374
Iteration 161, loss = 0.52774870
Iteration 162, loss = 0.52688365
Iteration 163, loss = 0.52594489
Iteration 164, loss = 0.52512807
Iteration 165, loss = 0.52418964
Iteration 166, loss = 0.52334339
Iteration 167, loss = 0.52248451
Iteration 168, loss = 0.52159276
Iteration 169, loss = 0.52072999
Iteration 170, loss = 0.51989446
Iteration 171, loss = 0.51902666
Iteration 172, loss = 0.51819398
Iteration 173, loss = 0.51738650
Iteration 174, loss = 0.51646292
Iteration 175, loss = 0.51560067
Iteration 176, loss = 0.51470863
Iteration 177, loss = 0.51391386
Iteration 178, loss = 0.51303648
Iteration 179, loss = 0.51223167
Iteration 180, loss = 0.51135585
Iteration 181, loss = 0.51052318
Iteration 182, loss = 0.50974162
Iteration 183, loss = 0.50893163
Iteration 184, loss = 0.50805950
Iteration 185, loss = 0.50731097
Iteration 186, loss = 0.50647411
Iteration 187, loss = 0.50569984
Iteration 188, loss = 0.50484757
Iteration 189, loss = 0.50404587
Iteration 190, loss = 0.50326533
Iteration 191, loss = 0.50247842
Iteration 192, loss = 0.50174349
Iteration 193, loss = 0.50098609
Iteration 194, loss = 0.50019752
Iteration 195, loss = 0.49945681
Iteration 196, loss = 0.49871824
Iteration 197, loss = 0.49798146
Iteration 198, loss = 0.49724770
Iteration 199, loss = 0.49650469
Iteration 200, loss = 0.49584225
Iteration 201, loss = 0.49510460
Iteration 202, loss = 0.49441987
Iteration 203, loss = 0.49368930
Iteration 204, loss = 0.49296146
Iteration 205, loss = 0.49226230
Iteration 206, loss = 0.49156109
Iteration 207, loss = 0.49084414
Iteration 208, loss = 0.49018237
Iteration 209, loss = 0.48947355
Iteration 210, loss = 0.48878799
Iteration 211, loss = 0.48806938
Iteration 212, loss = 0.48735091
Iteration 213, loss = 0.48668088
Iteration 214, loss = 0.48590377
Iteration 215, loss = 0.48520709
Iteration 216, loss = 0.48449161
Iteration 217, loss = 0.48375390
Iteration 218, loss = 0.48307444
Iteration 219, loss = 0.48235668
Iteration 220, loss = 0.48165221
Iteration 221, loss = 0.48096620
Iteration 222, loss = 0.48035173
Iteration 223, loss = 0.47963421
Iteration 224, loss = 0.47894184
Iteration 225, loss = 0.47830669
Iteration 226, loss = 0.47763753
Iteration 227, loss = 0.47697216
Iteration 228, loss = 0.47631747
Iteration 229, loss = 0.47564691
Iteration 230, loss = 0.47500714
Iteration 231, loss = 0.47432061
Iteration 232, loss = 0.47375493
Iteration 233, loss = 0.47308532
Iteration 234, loss = 0.47241001
Iteration 235, loss = 0.47181026
Iteration 236, loss = 0.47116914
Iteration 237, loss = 0.47052701
Iteration 238, loss = 0.46991312
Iteration 239, loss = 0.46932436
Iteration 240, loss = 0.46870549
Iteration 241, loss = 0.46807098
Iteration 242, loss = 0.46748073
Iteration 243, loss = 0.46688048
Iteration 244, loss = 0.46627960
Iteration 245, loss = 0.46566927
Iteration 246, loss = 0.46508158
Iteration 247, loss = 0.46446811
Iteration 248, loss = 0.46389782
Iteration 249, loss = 0.46330554
Iteration 250, loss = 0.46269782
Iteration 251, loss = 0.46208759
Iteration 252, loss = 0.46154276
Iteration 253, loss = 0.46098731
Iteration 254, loss = 0.46046207
Iteration 255, loss = 0.45983686
Iteration 256, loss = 0.45929329
Iteration 257, loss = 0.45871591
Iteration 258, loss = 0.45820294
Iteration 259, loss = 0.45762201
Iteration 260, loss = 0.45709808
Iteration 261, loss = 0.45660582
Iteration 262, loss = 0.45607296
Iteration 263, loss = 0.45558400
Iteration 264, loss = 0.45504502
Iteration 265, loss = 0.45457008
Iteration 266, loss = 0.45402955
Iteration 267, loss = 0.45355059
Iteration 268, loss = 0.45303079
Iteration 269, loss = 0.45256558
Iteration 270, loss = 0.45208953
Iteration 271, loss = 0.45157470
Iteration 272, loss = 0.45110728
Iteration 273, loss = 0.45058593
Iteration 274, loss = 0.45012627
Iteration 275, loss = 0.44966386
Iteration 276, loss = 0.44917458
Iteration 277, loss = 0.44872213
Iteration 278, loss = 0.44828597
Iteration 279, loss = 0.44784431
Iteration 280, loss = 0.44735985
Iteration 281, loss = 0.44690774
Iteration 282, loss = 0.44648017
Iteration 283, loss = 0.44602522
Iteration 284, loss = 0.44563386
Iteration 285, loss = 0.44518366
Iteration 286, loss = 0.44476429
Iteration 287, loss = 0.44435752
Iteration 288, loss = 0.44393388
Iteration 289, loss = 0.44355945
Iteration 290, loss = 0.44311981
Iteration 291, loss = 0.44271554
Iteration 292, loss = 0.44232144
Iteration 293, loss = 0.44192652
Iteration 294, loss = 0.44151957
Iteration 295, loss = 0.44111689
Iteration 296, loss = 0.44074259
Iteration 297, loss = 0.44036696
Iteration 298, loss = 0.43997046
Iteration 299, loss = 0.43957775
Iteration 300, loss = 0.43920304
Iteration 301, loss = 0.43884969
Iteration 302, loss = 0.43841899
Iteration 303, loss = 0.43804897
Iteration 304, loss = 0.43767918
Iteration 305, loss = 0.43727173
Iteration 306, loss = 0.43690907
Iteration 307, loss = 0.43651443
Iteration 308, loss = 0.43610794
Iteration 309, loss = 0.43572842
Iteration 310, loss = 0.43533378
Iteration 311, loss = 0.43497614
Iteration 312, loss = 0.43458481
Iteration 313, loss = 0.43422716
Iteration 314, loss = 0.43383216
Iteration 315, loss = 0.43347216
Iteration 316, loss = 0.43309536
Iteration 317, loss = 0.43273557
Iteration 318, loss = 0.43238244
Iteration 319, loss = 0.43195965
Iteration 320, loss = 0.43163242
Iteration 321, loss = 0.43123776
Iteration 322, loss = 0.43087184
Iteration 323, loss = 0.43049806
Iteration 324, loss = 0.43016935
Iteration 325, loss = 0.42978113
Iteration 326, loss = 0.42940198
Iteration 327, loss = 0.42905498
Iteration 328, loss = 0.42866166
Iteration 329, loss = 0.42835543
Iteration 330, loss = 0.42799175
Iteration 331, loss = 0.42764757
Iteration 332, loss = 0.42732101
Iteration 333, loss = 0.42700161
Iteration 334, loss = 0.42668160
Iteration 335, loss = 0.42631685
Iteration 336, loss = 0.42602468
Iteration 337, loss = 0.42567798
Iteration 338, loss = 0.42536577
Iteration 339, loss = 0.42505696
Iteration 340, loss = 0.42475693
Iteration 341, loss = 0.42440806
Iteration 342, loss = 0.42411271
Iteration 343, loss = 0.42376756
Iteration 344, loss = 0.42347517
Iteration 345, loss = 0.42315068
Iteration 346, loss = 0.42286582
Iteration 347, loss = 0.42255156
Iteration 348, loss = 0.42228541
Iteration 349, loss = 0.42192919
Iteration 350, loss = 0.42166389
Iteration 351, loss = 0.42131515
Iteration 352, loss = 0.42104598
Iteration 353, loss = 0.42077542
Iteration 354, loss = 0.42043657
Iteration 355, loss = 0.42017513
Iteration 356, loss = 0.41985620
Iteration 357, loss = 0.41955086
Iteration 358, loss = 0.41925099
Iteration 359, loss = 0.41900061
Iteration 360, loss = 0.41871305
Iteration 361, loss = 0.41840905
Iteration 362, loss = 0.41814285
Iteration 363, loss = 0.41787761
Iteration 364, loss = 0.41760059
Iteration 365, loss = 0.41734304
Iteration 366, loss = 0.41702509
Iteration 367, loss = 0.41678167
Iteration 368, loss = 0.41650300
Iteration 369, loss = 0.41623051
Iteration 370, loss = 0.41595478
Iteration 371, loss = 0.41567746
Iteration 372, loss = 0.41541819
Iteration 373, loss = 0.41512957
Iteration 374, loss = 0.41489316
Iteration 375, loss = 0.41459408
Iteration 376, loss = 0.41434924
Iteration 377, loss = 0.41407795
Iteration 378, loss = 0.41385403
Iteration 379, loss = 0.41358540
Iteration 380, loss = 0.41333492
Iteration 381, loss = 0.41310034
Iteration 382, loss = 0.41286897
Iteration 383, loss = 0.41260156
Iteration 384, loss = 0.41236342
Iteration 385, loss = 0.41213174
Iteration 386, loss = 0.41190695
Iteration 387, loss = 0.41171878
Iteration 388, loss = 0.41139790
Iteration 389, loss = 0.41119170
Iteration 390, loss = 0.41095521
Iteration 391, loss = 0.41072230
Iteration 392, loss = 0.41049986
Iteration 393, loss = 0.41026883
Iteration 394, loss = 0.40999878
Iteration 395, loss = 0.40976587
Iteration 396, loss = 0.40953608
Iteration 397, loss = 0.40932679
Iteration 398, loss = 0.40908059
Iteration 399, loss = 0.40882800
Iteration 400, loss = 0.40863281
Iteration 401, loss = 0.40836630
Iteration 402, loss = 0.40815637
Iteration 403, loss = 0.40793217
Iteration 404, loss = 0.40770959
Iteration 405, loss = 0.40747145
Iteration 406, loss = 0.40729432
Iteration 407, loss = 0.40701455
Iteration 408, loss = 0.40685143
Iteration 409, loss = 0.40659437
Iteration 410, loss = 0.40636982
Iteration 411, loss = 0.40618302
Iteration 412, loss = 0.40594553
Iteration 413, loss = 0.40571854
Iteration 414, loss = 0.40552380
Iteration 415, loss = 0.40528065
Iteration 416, loss = 0.40506047
Iteration 417, loss = 0.40486322
Iteration 418, loss = 0.40470110
Iteration 419, loss = 0.40442804
Iteration 420, loss = 0.40427811
Iteration 421, loss = 0.40402748
Iteration 422, loss = 0.40381919
Iteration 423, loss = 0.40359789
Iteration 424, loss = 0.40343730
Iteration 425, loss = 0.40319947
Iteration 426, loss = 0.40299681
Iteration 427, loss = 0.40277341
Iteration 428, loss = 0.40259475
Iteration 429, loss = 0.40239832
Iteration 430, loss = 0.40223113
Iteration 431, loss = 0.40201119
Iteration 432, loss = 0.40180553
Iteration 433, loss = 0.40162540
Iteration 434, loss = 0.40140607
Iteration 435, loss = 0.40122604
Iteration 436, loss = 0.40104143
Iteration 437, loss = 0.40084580
Iteration 438, loss = 0.40069724
Iteration 439, loss = 0.40048577
Iteration 440, loss = 0.40028175
Iteration 441, loss = 0.40012400
Iteration 442, loss = 0.39993141
Iteration 443, loss = 0.39972650
Iteration 444, loss = 0.39955514
Iteration 445, loss = 0.39937040
Iteration 446, loss = 0.39924072
Iteration 447, loss = 0.39908948
Iteration 448, loss = 0.39884775
Iteration 449, loss = 0.39867189
Iteration 450, loss = 0.39854174
Iteration 451, loss = 0.39834251
Iteration 452, loss = 0.39814328
Iteration 453, loss = 0.39800122
Iteration 454, loss = 0.39781887
Iteration 455, loss = 0.39762494
Iteration 456, loss = 0.39746975
Iteration 457, loss = 0.39730173
Iteration 458, loss = 0.39712439
Iteration 459, loss = 0.39695514
Iteration 460, loss = 0.39678824
Iteration 461, loss = 0.39662378
Iteration 462, loss = 0.39645594
Iteration 463, loss = 0.39635784
Iteration 464, loss = 0.39611496
Iteration 465, loss = 0.39595506
Iteration 466, loss = 0.39578802
Iteration 467, loss = 0.39564875
Iteration 468, loss = 0.39549812
Iteration 469, loss = 0.39530936
Iteration 470, loss = 0.39520382
Iteration 471, loss = 0.39502253
Iteration 472, loss = 0.39482338
Iteration 473, loss = 0.39466163
Iteration 474, loss = 0.39454839
Iteration 475, loss = 0.39437956
Iteration 476, loss = 0.39421858
Iteration 477, loss = 0.39403483
Iteration 478, loss = 0.39392911
Iteration 479, loss = 0.39374941
Iteration 480, loss = 0.39362041
Iteration 481, loss = 0.39343898
Iteration 482, loss = 0.39332022
Iteration 483, loss = 0.39311722
Iteration 484, loss = 0.39298938
Iteration 485, loss = 0.39283782
Iteration 486, loss = 0.39273036
Iteration 487, loss = 0.39254614
Iteration 488, loss = 0.39238385
Iteration 489, loss = 0.39222641
Iteration 490, loss = 0.39209217
Iteration 491, loss = 0.39195890
Iteration 492, loss = 0.39182816
Iteration 493, loss = 0.39163875
Iteration 494, loss = 0.39151131
Iteration 495, loss = 0.39136824
Iteration 496, loss = 0.39120593
Iteration 497, loss = 0.39108619
Iteration 498, loss = 0.39091362
Iteration 499, loss = 0.39076425
Iteration 500, loss = 0.39063359
Iteration 501, loss = 0.39047903
Iteration 502, loss = 0.39031839
Iteration 503, loss = 0.39019573
Iteration 504, loss = 0.39003921
Iteration 505, loss = 0.38990357
Iteration 506, loss = 0.38976339
Iteration 507, loss = 0.38966460
Iteration 508, loss = 0.38948780
Iteration 509, loss = 0.38932517
Iteration 510, loss = 0.38920380
Iteration 511, loss = 0.38907461
Iteration 512, loss = 0.38893764
Iteration 513, loss = 0.38877784
Iteration 514, loss = 0.38864041
Iteration 515, loss = 0.38849352
Iteration 516, loss = 0.38836598
Iteration 517, loss = 0.38821652
Iteration 518, loss = 0.38807949
Iteration 519, loss = 0.38798458
Iteration 520, loss = 0.38781354
Iteration 521, loss = 0.38766517
Iteration 522, loss = 0.38753509
Iteration 523, loss = 0.38746142
Iteration 524, loss = 0.38727288
Iteration 525, loss = 0.38721172
Iteration 526, loss = 0.38699362
Iteration 527, loss = 0.38687336
Iteration 528, loss = 0.38674389
Iteration 529, loss = 0.38663063
Iteration 530, loss = 0.38647426
Iteration 531, loss = 0.38634330
Iteration 532, loss = 0.38623083
Iteration 533, loss = 0.38612232
Iteration 534, loss = 0.38597246
Iteration 535, loss = 0.38586969
Iteration 536, loss = 0.38570874
Iteration 537, loss = 0.38559957
Iteration 538, loss = 0.38546741
Iteration 539, loss = 0.38534701
Iteration 540, loss = 0.38522746
Iteration 541, loss = 0.38508487
Iteration 542, loss = 0.38496604
Iteration 543, loss = 0.38484015
Iteration 544, loss = 0.38469878
Iteration 545, loss = 0.38458871
Iteration 546, loss = 0.38446907
Iteration 547, loss = 0.38434037
Iteration 548, loss = 0.38427493
Iteration 549, loss = 0.38412405
Iteration 550, loss = 0.38400791
Iteration 551, loss = 0.38387088
Iteration 552, loss = 0.38373134
Iteration 553, loss = 0.38363015
Iteration 554, loss = 0.38350899
Iteration 555, loss = 0.38338497
Iteration 556, loss = 0.38325808
Iteration 557, loss = 0.38318576
Iteration 558, loss = 0.38302977
Iteration 559, loss = 0.38290434
Iteration 560, loss = 0.38277883
Iteration 561, loss = 0.38265887
Iteration 562, loss = 0.38254445
Iteration 563, loss = 0.38239233
Iteration 564, loss = 0.38228858
Iteration 565, loss = 0.38218280
Iteration 566, loss = 0.38204891
Iteration 567, loss = 0.38193544
Iteration 568, loss = 0.38181473
Iteration 569, loss = 0.38169371
Iteration 570, loss = 0.38157494
Iteration 571, loss = 0.38145700
Iteration 572, loss = 0.38136369
Iteration 573, loss = 0.38124408
Iteration 574, loss = 0.38113582
Iteration 575, loss = 0.38100749
Iteration 576, loss = 0.38088690
Iteration 577, loss = 0.38078958
Iteration 578, loss = 0.38066592
Iteration 579, loss = 0.38056287
Iteration 580, loss = 0.38042451
Iteration 581, loss = 0.38034102
Iteration 582, loss = 0.38020447
Iteration 583, loss = 0.38010094
Iteration 584, loss = 0.38000681
Iteration 585, loss = 0.37988645
Iteration 586, loss = 0.37979374
Iteration 587, loss = 0.37965923
Iteration 588, loss = 0.37955883
Iteration 589, loss = 0.37942830
Iteration 590, loss = 0.37931602
Iteration 591, loss = 0.37921754
Iteration 592, loss = 0.37912233
Iteration 593, loss = 0.37899521
Iteration 594, loss = 0.37888918
Iteration 595, loss = 0.37879512
Iteration 596, loss = 0.37869547
Iteration 597, loss = 0.37857894
Iteration 598, loss = 0.37844619
Iteration 599, loss = 0.37835489
Iteration 600, loss = 0.37824718
Iteration 601, loss = 0.37812494
Iteration 602, loss = 0.37804599
Iteration 603, loss = 0.37792817
Iteration 604, loss = 0.37783064
Iteration 605, loss = 0.37769299
Iteration 606, loss = 0.37762477
Iteration 607, loss = 0.37751204
Iteration 608, loss = 0.37738124
Iteration 609, loss = 0.37729481

MLPClassifier(alpha=0.001, batch_size=32, hidden_layer_sizes=12,
              learning_rate_init=0.0001, max_iter=1000, random_state=42,
              verbose=True)

In [21]:
# evaluate the model
y_pred = model.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87        29
           1       0.90      0.84      0.87        32

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61

In [22]:
# save the trained model
dump(model, '../models/model.joblib')

['../models/model.joblib']

### Inference

In [23]:
# Usiamo 'x' (dati pre-processamento) per prendere una riga media come test
test_row_values = x.mean()
# Creiamo un DataFrame con questa riga
test_df = pd.DataFrame([test_row_values], columns=x.columns) # IMPORTANTE: deve essere un DataFrame

# load the scaler (preprocessor) and model
preprocessor = load('../models/preprocessor_heart.joblib')
model = load('../models/model_heart.joblib')

# transform the new data
# Il preprocessor si aspetta il DataFrame
features_test_processed = preprocessor.transform(test_df)

# make a prediction
if (model.predict(features_test_processed)==0):
    print("Predizione: Basse probabilità di infarto.")
else:
    print("Predizione: Alte probabilità di infarto.")

Predizione: Basse probabilità di infarto.

C:\Users\sasyc\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(